FROM archlinux

RUN pacman -Syu --needed base-devel --noconfirm
RUN pacman -S vim git cmake ninja python3 --noconfirm

RUN git clone https://github.com/HakonHarnes/pluto-wasm-obfuscator.git

WORKDIR /pluto-wasm-obfuscator

RUN ./build.sh

ENV PATH="$PATH:/pluto-wasm-obfuscator/build/bin"

WORKDIR /

# RUN pacman -S wget nodejs 
#
# RUN wget https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz
#
# RUN tar -xvf binaryen-version_101-x86_64-linux.tar.gz
#
# RUN wget https://github.com/emscripten-core/emscripten/archive/refs/tags/2.0.26.tar.gz
#
# RUN tar -xvf 2.0.26.tar.gzo

