FROM archlinux

RUN pacman -Syu --needed base-devel --noconfirm
RUN pacman -S git cmake ninja python3 --noconfirm

RUN git clone https://github.com/bluesadi/Pluto-Obfuscator.git /pluto-obfuscator

WORKDIR /pluto-obfuscator

RUN ./build.sh

