services:
  verify-hashes:
    build: .
    volumes:
      - ./main.py:/app/main.py
      - ../binaries:/app/binaries
      - ../mongodb/utils.py:/app/mongodb/utils.py
    environment:
      - BINARY_PATH=/app/binaries
    networks:
      - db_network

networks:
  db_network:
    external: true
