version: "3"

services:
  tigress:
    build: ./tigress
    volumes:
      - ./tigress/main.py:/tigress/main.py
      - ../dataset/:/tigress/dataset
      - ../binaries:/tigress/binaries
    environment:
      - BINARY_PATH=/tigress/binaries
      - DATASET_PATH=/tigress/dataset
  llvm:
    build: ./llvm
    volumes:
      - ./llvm/main.py:/llvm/main.py
      - ../dataset/:/llvm/dataset
      - ../binaries:/llvm/binaries
    environment:
      - BINARY_PATH=/llvm/binaries
      - DATASET_PATH=/llvm/dataset
