services:
  tigress:
    build: ./tigress
    volumes:
      - ./tigress/main.py:/app/main.py
      - ../dataset/:/app/dataset
      - ../binaries:/app/binaries
      - ../mongodb/utils.py:/app/mongodb/utils.py
    environment:
      - BINARY_PATH=/app/binaries
      - DATASET_PATH=/app/dataset
    networks:
      - db_network
  llvm:
    build: ./llvm
    volumes:
      - ./llvm/main.py:/app/main.py
      - ../dataset/:/app/dataset
      - ../binaries:/app/binaries
      - ../mongodb/utils.py:/app/mongodb/utils.py
    environment:
      - BINARY_PATH=/app/binaries
      - DATASET_PATH=/app/dataset
    networks:
      - db_network
  wasm-mutate:
    build: ./wasm-mutate
    volumes:
      - ./wasm-mutate/main.py:/app/main.py
      - ../dataset/:/app/dataset
      - ../binaries:/app/binaries
      - ../mongodb/utils.py:/app/mongodb/utils.py
    environment:
      - BINARY_PATH=/app/binaries
      - DATASET_PATH=/app/dataset
    networks:
      - db_network

networks:
  db_network:
    external: true
