version: "3"

services:
  miner-ray:
    build: ./miner-ray
    volumes:
      - ./miner-ray/main.py:/app/main.py
      - ./miner-ray/src:/app/src
      - ../binaries:/app/binaries
      - ../data/:/app/data
      - ../utils/:/app/utils
  minos:
    build: ./minos
    volumes:
      - ./minos/main.py:/app/main.py
      - ../binaries:/app/binaries
      - ../data/:/app/data
      - ../utils/:/app/utils
    environment:
      - BINARY_PATH=/app/binaries
      - DATA_PATH=/app/data
  virustotal:
    build: ./virustotal
    volumes:
      - ./virustotal/main.py:/app/main.py
      - ./virustotal/.env:/app/.env
      - ../binaries:/app/binaries
      - ../data/:/app/data
      - ../utils/:/app/utils
